#!/usr/bin/env python3
"""Generate editor/po-funcnames.js — a per-locale {EnglishFuncName: LocalizedName} map.

WHY: the Collabora browser builds the notebookbar function dropdowns (Formulas tab →
Date & Time / Financial / Logical / Math & Trig / … ) from a STATIC table that only
localizes de/fr/es (`getLocalizedFuncName` in browser/src/control/jsdialog/Definitions.Menu.ts).
For every other locale it emits the ENGLISH name both as the visible label AND inside
`.uno:InsertFunction?FunctionName=<name>`. A localized LO core (e.g. RU) only accepts the
LOCALIZED name (СЕГОДНЯ, not TODAY) — so in RU the dropdown shows English AND fails to insert.

The localized names live in the LO core gettext catalogs (same source the Function Wizard
uses). This script extracts them straight from the RUNNING editor container and emits a plain
global JS map that a source patch to `getLocalizedFuncName` consults (delivered like po-toggle.js,
loaded before bundle.js so the map exists when the menus are built). Regenerate on every re-pin.

Source modules (per locale dir under /opt/collaboraoffice/program/resource/<dir>/LC_MESSAGES/):
  for.mo  — builtin Calc functions, msgctxt=RID_STRLIST_FUNCTION_NAMES  (msgid=EN, msgstr=localized)
  sca.mo  — add-in functions,       msgctxt=*_FUNCNAME_*

Output: editor/po-funcnames.js  ->  window.PO_FN_NAMES = { "<locale>": { "TODAY": "СЕГОДНЯ", … }, … }
Map keys are lowercased with '-'->'_' so they match a normalized String.locale in the browser.
Only entries where the localized name DIFFERS from English are kept (the browser falls back to the
English name otherwise), which keeps the file small.

Run: python3 scripts/build-l10n-funcnames.py            # all shipped locales, from the running editor
"""
import gettext
import json
import os
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CORE = "/opt/collaboraoffice/program/resource"
OUT = os.path.join(ROOT, "editor", "po-funcnames.js")

# Locales we ship client overrides for (editor/l10n/overrides/client/*.json). The filename IS the
# LO resource-dir name (pt_BR matches). de/es are intentionally omitted — the upstream static table
# already covers them; fr is included (map value == static value, harmless).
LOCALES = ["ar", "cs", "fr", "he", "it", "ja", "ko", "pt_BR", "ru", "tr", "uk", "vi"]


def editor_container():
    cid = subprocess.run(["docker", "compose", "ps", "-q", "editor"],
                         cwd=ROOT, capture_output=True, text=True).stdout.strip()
    if not cid:
        sys.exit("editor container is not running (./scripts/up.sh editor)")
    return cid


def docker_cp(cid, src, dst):
    return subprocess.run(["docker", "cp", f"{cid}:{src}", dst],
                          capture_output=True, text=True).returncode == 0


def funcnames_from_mo(path, ctxt_pred):
    """Return {english_msgid: localized_msgstr} for entries whose msgctxt passes ctxt_pred."""
    out = {}
    with open(path, "rb") as fh:
        tr = gettext.GNUTranslations(fh)
    for key, val in tr._catalog.items():
        if not key or isinstance(key, tuple):
            continue
        msgctxt, msgid = (key.split("\x04", 1) if "\x04" in key else (None, key))
        if not msgid or not val or not msgctxt or not ctxt_pred(msgctxt):
            continue
        out[msgid] = val
    return out


def main():
    cid = editor_container()
    all_maps = {}
    stats = {}
    with tempfile.TemporaryDirectory() as tmp:
        for loc in LOCALES:
            m = {}
            for mod, pred in (("for", lambda c: c == "RID_STRLIST_FUNCTION_NAMES"),
                              ("sca", lambda c: "_FUNCNAME_" in c)):
                dst = os.path.join(tmp, f"{loc}-{mod}.mo")
                src = f"{CORE}/{loc}/LC_MESSAGES/{mod}.mo"
                if docker_cp(cid, src, dst):
                    m.update(funcnames_from_mo(dst, pred))
            # keep only real translations (localized != english); browser falls back to EN otherwise
            m = {en: loc_name for en, loc_name in m.items() if loc_name and loc_name != en}
            key = loc.lower().replace("-", "_")
            all_maps[key] = m
            stats[key] = len(m)

    payload = json.dumps(all_maps, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    header = ("/* GENERATED by scripts/build-l10n-funcnames.py — do not edit by hand.\n"
              "   Localized Calc function names extracted from the LO core (for.mo + sca.mo).\n"
              "   Consumed by the getLocalizedFuncName source patch so notebookbar function\n"
              "   dropdowns show localized names AND insert correctly in every locale.\n"
              "   Regenerate after re-pinning the engine. */\n")
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(header)
        fh.write("window.PO_FN_NAMES=" + payload + ";\n")

    print(f"wrote {OUT}")
    print("entries per locale:", json.dumps(stats, ensure_ascii=False))
    # spot-check
    ru = all_maps.get("ru", {})
    for probe in ("TODAY", "NOW", "SUM", "VLOOKUP", "NETWORKDAYS.INTL"):
        print(f"  ru {probe!r} -> {ru.get(probe, '<none>')!r}")


if __name__ == "__main__":
    main()
