#!/usr/bin/env python3
"""Generate editor/po-stylenames.js — a per-locale {EnglishCellStyleName: LocalizedName} map.

WHY: the Collabora browser shows built-in Calc CELL STYLE names (Good, Bad, Neutral, Accent,
Accent 1/2/3, Heading, Heading 1/2, Result, Status, Text, Warning, Error, Footnote, Hyperlink, Note)
in ENGLISH in the sidebar Styles deck, the Conditional-Formatting "Apply Style" dropdown, and the
style boxes — even though the LO core ships the translations. The style-list path sends the style's
INTERNAL English name (only "Default" is core-localized → "Базовый"). We localize the DISPLAY text on
the browser side (a source patch consuming window.PO_STYLE_NAMES) while keeping the underlying value
English so applying a style still round-trips to the core. A map lookup only hits built-in English
names, so user-defined (custom) styles pass through untouched.

Mirror of scripts/build-l10n-funcnames.py — same extraction machinery, different module + msgctxt.

Source module (per LO resource dir /opt/collaboraoffice/program/resource/<dir>/LC_MESSAGES/):
  sc.mo — msgctxt=STR_STYLENAME_*  (msgid=EN cell-style name, msgstr=localized)

Output: editor/po-stylenames.js  ->  window.PO_STYLE_NAMES = { "<locale>": { "Good": "Хорошо", … }, … }
Keys lowercased '-'->'_'; a base-language alias is added (pt->pt_BR) so a normalized String.locale hits
with or without region. Only entries whose localized name DIFFERS from English are kept. Regenerate on
every re-pin.

Run: python3 scripts/build-l10n-stylenames.py            # all supported locales, from the running editor
"""
import gettext
import json
import os
import re
import subprocess
import sys
import tempfile

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
CORE = "/opt/collaboraoffice/program/resource"
OUT = os.path.join(ROOT, "editor", "po-stylenames.js")
LOCALES_PY = os.path.join(ROOT, "backend", "app", "services", "locales.py")

# App locale code -> LO resource-dir name where they differ (region uppercased). Everything else 1:1.
LO_DIR = {"pt-BR": "pt_BR", "zh-CN": "zh_CN", "zh-TW": "zh_TW"}


def supported_locales():
    """Read SUPPORTED codes from backend/app/services/locales.py (source of truth), minus 'en'."""
    text = open(LOCALES_PY, encoding="utf-8").read()
    block = re.search(r"SUPPORTED[^{]*\{(.*?)\n\}", text, re.S)
    codes = re.findall(r'"([A-Za-z-]+)"\s*:', block.group(1)) if block else []
    return [c for c in codes if c != "en"]


def editor_container():
    cid = subprocess.run(["docker", "compose", "ps", "-q", "editor"],
                         cwd=ROOT, capture_output=True, text=True).stdout.strip()
    if not cid:
        sys.exit("editor container is not running (./scripts/up.sh editor)")
    return cid


def docker_cp(cid, src, dst):
    return subprocess.run(["docker", "cp", f"{cid}:{src}", dst],
                          capture_output=True, text=True).returncode == 0


def stylenames_from_mo(path):
    """Return {english_msgid: localized_msgstr} for entries whose msgctxt starts with STR_STYLENAME_."""
    out = {}
    with open(path, "rb") as fh:
        tr = gettext.GNUTranslations(fh)
    for key, val in tr._catalog.items():
        if not key or isinstance(key, tuple):
            continue
        if "\x04" not in key:
            continue
        msgctxt, msgid = key.split("\x04", 1)
        if msgid and val and msgctxt.startswith("STR_STYLENAME_"):
            out[msgid] = val
    return out


def main():
    cid = editor_container()
    codes = supported_locales()
    all_maps = {}
    stats = {}
    with tempfile.TemporaryDirectory() as tmp:
        for code in codes:
            lo = LO_DIR.get(code, code)
            dst = os.path.join(tmp, f"{lo}-sc.mo")
            if not docker_cp(cid, f"{CORE}/{lo}/LC_MESSAGES/sc.mo", dst):
                continue
            m = stylenames_from_mo(dst)
            # keep only real translations (localized != english); browser falls back to EN otherwise
            m = {en: loc for en, loc in m.items() if loc and loc != en}
            # Drop "Default": the deck sends it already core-localized ("Базовый"), so it is never
            # looked up here — but the patch scopes on the generic treeview id 'treeview' (hierarchical
            # styles view), and "Default" is a common non-style entry elsewhere whose style translation
            # ("Базовый") would be wrong. Every other key is style-specific enough to be safe.
            m.pop("Default", None)
            if not m:
                continue
            key = code.lower().replace("-", "_")
            all_maps[key] = m
            all_maps.setdefault(key.split("_")[0], m)  # base-language alias (pt->pt_BR, zh->zh_CN)
            stats[key] = len(m)

    payload = json.dumps(all_maps, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    header = ("/* GENERATED by scripts/build-l10n-stylenames.py — do not edit by hand.\n"
              "   Localized built-in Calc cell-style names extracted from the LO core (sc.mo,\n"
              "   msgctxt STR_STYLENAME_*) for every app-supported locale that has an LO catalog.\n"
              "   Consumed by the style-name localization source patch (editor/patches/0004-*) so the\n"
              "   sidebar Styles deck + the Conditional-Formatting Apply-Style dropdown show localized\n"
              "   names while the applied value stays English. Regenerate after re-pinning the engine. */\n")
    # window.getPOStyleName(name): display-only lookup keyed on the current locale (mirrors
    # getLocalizedFuncName's String.locale normalization). Returns the localized built-in style name,
    # or the input unchanged when it is not a built-in name (so custom/user styles pass through). The
    # source patch calls this ONLY inside the style widgets (treeview id 'flatview', listbox id 'style'),
    # so there is no collateral translation of unrelated lists.
    helper = (
        "window.getPOStyleName=function(name){"
        "var maps=window.PO_STYLE_NAMES;if(!maps||!name)return name;"
        "var loc='en';try{if(String.locale)loc=String.locale;}catch(e){}"
        "loc=String(loc).toLowerCase().replace(/-/g,'_');"
        "var m=maps[loc]||maps[loc.split('_')[0]];"
        "return (m&&m[name])||name;};\n"
    )
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write(header)
        fh.write("window.PO_STYLE_NAMES=" + payload + ";\n")
        fh.write(helper)

    print(f"wrote {OUT}")
    print(f"supported (from locales.py): {codes}")
    print("entries per locale:", json.dumps(stats, ensure_ascii=False))
    for loc in ("ru", "nl", "pl", "zh_cn"):
        mp = all_maps.get(loc, {})
        print(f"  {loc} Good -> {mp.get('Good', '<none>')!r} | Accent 1 -> {mp.get('Accent 1', '<none>')!r} | count={len(mp)}")


if __name__ == "__main__":
    main()
